project_name: opg-terraform-workspace-manager

env_files:
  github_token: ${{ secrets.GITHUB_TOKEN }}

release:
  prerelease: auto
  github:
    owner: ministryofjustice
    name: opg-terraform-workspace-manager

builds:
  - binary: terraform-workspace-manager
    id: terraform-workspace-manager
    main: ./main.go
    goos:
      - freebsd
      - openbsd
      - solaris
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
archives:
  - name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'