project_name: opg-terraform-workspace-manager

env_files:
  github_token: ${{ secrets.GITHUB_TOKEN }}

release:
  prerelease: auto
  github:
    owner: ministryofjustice
    name: opg-terraform-workspace-manager

builds:
  - binary: terraform-workspace-manager
    id: terraform-workspace-manager
    main: ./main.go
    goos:
      - freebsd
      - openbsd
      - solaris
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
archives:
  - name_template: '{{- .ProjectName }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end -}}'