name: Release
on:
  push:
      branches:
        - "!*"
      tags:
        - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      - id: checkout
        name: Checkout code into the go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: go
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - name: release
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
